### ISSUE TITLE
Running on windows

### ISSUE THREAD

**Issue by Oussamaaat** [taroz/gsdc2023#1]
Hello Mr Taro thanks for providing the code along with the paper it is very interesting !

Has anyone tried building the repo with msys2 or visual studio on windows 10 or 11?

Any help or tutorial would be much appreciated !!

**Comment by Oussamaaat** [comment]
The following steps seems to succesfully build on windows (run everything as admin): 

1. Install Visual studio 2022 (make sure to include c++ cmake for windows)
2.  Install cmake from https://cmake.org/download/ (i used the msi file) (maybe this is a useless step because of step 1 ?!)
3. Install boost from https://www.boost.org/users/history/version_1_86_0.html follow this tutorial : https://www.youtube.com/watch?v=3elKoMMuJBA
4. Install tbb from https://www.intel.com/content/www/us/en/developer/tools/oneapi/onetbb-download.html
5. Install mkl from https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-download.html
6. Execute C:\Program Files (x86)\Intel\oneAPI\tbb\latest\env\vars.bat
7. Execute C:\Program Files (x86)\Intel\oneAPI\mkl\latest\env\vars.bat
8. Have Pyhton installed and the package pyparsing (`pip install pyparsing`)
10. Reboot your computer

Then go to an empty folder and open in a terminal (i used powershell as admin) : 

```
git clone https://github.com/borglab/gtsam.git
cd gtsam
git checkout 4.0.3
mkdir build
cd build 
cmake .. -DCMAKE_BUILD_TYPE=Release -DGTSAM_BUILD_UNSTABLE:OPTION=OFF -DGTSAM_BUILD_EXAMPLES_ALWAYS:OPTION=OFF -DGTSAM_INSTALL_MATLAB_TOOLBOX:OPTION=ON -G "Visual Studio 17 2022" -A x64
cmake --build . --config Release
cmake --install . --config Release
```

If you get an error related to boost try reinstalling it using msys2 by running the following
```
pacman -Syu
pacman -S mingw-w64-x86_64-toolchain cmake make git
pacman -S mingw-w64-x86_64-boost
```
Then repeat the steps in a new empty build folder using porwershell

There are some redundant steps but at least you make sure to have everything, any suggestions are welcome !!
Also i only built gtsam but still not sure if its running correctly, i'm still facing the issue #2 😵

**Comment by taroz** [comment]
Thanks for the post. You may not need MKL for building gtsam, but I think it's generally fine.

When I set up the gtsam environment on Windows, I don't use TBB because it gives an unknown error at runtime, and for Boost I install pre-built binaries from the following site.
https://boost.teeks99.com/

To run the gsdc2023 source code on a Windows environment, you need to build gtsam_gnss, which is a MATLAB wrapper, on Windows, but the source code is not currently available.

As the problem with the latest MATLAB Wrapper for gtsam has now been resolved, I have changed the version of gtsam used by gsdc2023 to 4.3a, and am currently preparing to provide gtsam_gnss in a separate repository by the end of this month. I am also preparing a tutorial on how to build gtsam and gtsam_gnss on Windows, so please wait a little longer.

**Comment by Oussamaaat** [comment]
Okay i understand, thank you very much for your feedback !

**Comment by taroz** [comment]
@Oussamaaat Ihave upgraded GTSAM (from 4.03 to 4.3a) and moved the execution environment from Ubuntu 20.04 to Ubuntu 22.04. We have also added Windows support. Please check it out!

**Comment by Oussamaaat** [comment]
Thank you very much @taroz, i tried the example on windows and it works, no problems encountered.
