### ISSUE TITLE
Build Failure: Please specify the required version of libtbb-dev

### ISSUE THREAD

**Issue by yukiu00** [taroz/gsdc2023#4]
I encountered a build failure when trying to compile the project following the instructions in the README. `cmake .. -DCMAKE_BUILD_TYPE=Release -DGTSAM_BUILD_UNSTABLE:OPTION=OFF -DGTSAM_BUILD_EXAMPLES_ALWAYS:OPTION=OFF -DGTSAM_INSTALL_MATLAB_TOOLBOX:OPTION=ON` The error indicates an issue with TBB:

```
CMake Error at cmake/FindTBB.cmake:187 (file):
  file failed to open for reading (No such file or directory):
    /usr/include/tbb/tbb_stddef.h
Call Stack (most recent call first):
  CMakeLists.txt:199 (find_package)
```

My environment:

OS: Ubuntu 22.04
libtbb-dev version: 2021.5.0-7ubuntu2
CMake version: 3.22.1
From the error, it seems that the tbb_stddef.h file is missing, even though libtbb-dev is installed on my system. Could you confirm the required version of TBB for this project and whether additional steps are needed to ensure compatibility?

Additionally, I checked out the latest develop branch, and I noticed that this error does not occur there.

Thank you for your assistance!

**Comment by taroz** [comment]
Thanks for the report.

This problem occurs because Ubuntu 22.04 installs a newer version of TBB. The older version, GTSAM 4.0.3, cannot handle the newer TBB version. The easiest way to deal with this problem is to use Ubuntu 20.04.

I tried to see if I could build GTSAM 4.03 on Ubuntu 22.04, but it seems that there is a problem not only with TBB but also with the version of Boost. As it doesn't look like it will be solved anytime soon, could you please try testing gsdc2023 on an **Ubuntu 20.04** for now?

In any case, I am currently trying to switch to the latest version of GTASM for use with gsdc2023. In that case, the supported environment will be Ubuntu 22.04, and you will not need to worry about these issues.

**Comment by taroz** [comment]
We have upgraded GTSAM (from 4.03 to 4.3a) and moved the execution environment from Ubuntu 20.04 to Ubuntu 22.04. Please check it out!
